//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIITWaitingQueueSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingSchedule
    {
        public int meeting_id { get; set; }
        public Nullable<int> group_no { get; set; }
        public string reg_no { get; set; }
        public string std_name { get; set; }
        public string std_gender { get; set; }
        public string std_class { get; set; }
        public string std_supervisor { get; set; }
        public string project_title { get; set; }
        public string technology { get; set; }
        public string meeting_time { get; set; }
        public string meeting_date { get; set; }
        public Nullable<int> meeting_status { get; set; }
        public Nullable<int> fyp { get; set; }
        public string remarks { get; set; }
    }
}
