//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIITWaitingQueueSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reschedule_Requests
    {
        public int req_id { get; set; }
        public string req_msg { get; set; }
        public string std_name { get; set; }
        public string std_reg_no { get; set; }
        public string std_cls { get; set; }
        public Nullable<int> msg_status { get; set; }
        public string std_supervisor { get; set; }
    }
}
