//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIITWaitingQueueSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int std_id { get; set; }
        public string std_regno { get; set; }
        public string std_fullname { get; set; }
        public string std_supervisor { get; set; }
        public string std_email { get; set; }
        public string std_address { get; set; }
        public string std_phoneno { get; set; }
        public string std_password { get; set; }
    }
}
